namespace: dev-native

resources:
- faucet.yml
- ingress.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: faucet-estake
    envs:
      - configs/.elysium.env
  - name: faucet-gaia
    envs:
      - configs/.cosmos.env
